function [fitresult, gof] = modVsDistFits(distances, means, stds,type)
%CREATEFIT1(DISTANCES,AWMEANHIGH,AWERRHIGH)
%  Create a fit.
%
%  Data for 'AW High Para' fit:
%      X Input: distances
%      Y Output: awMeanHigh
%      Weights: awErrHigh
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Aug-2023 23:08:33 + AD


%% Fit: 'AW High Para'.
[xData, yData, weights] = prepareCurveData( distances, means, stds );

% Set up fittype and options.

ft = fittype(type);
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'on';
opts.Weights = exp(weights);
%opts.MaxIter = 1e6;
%opts.MaxFunEvals = 1e6;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure;
h = plot(fitresult, xData, yData);
%legend(h, 'awMeanHigh vs. distances with awErrHigh', 'AW High Para', 'Location', 'NorthEast', 'Interpreter', 'none');
% Label axes
%xlabel( 'distances', 'Interpreter', 'none' );
%ylabel( 'awMeanHigh', 'Interpreter', 'none' );
grid on